version: "3.7"
services:

  db:
    container_name: dj_demo_app_postgres_container
    image: "postgres" # use latest official postgres version
    ports:
      # let's Docker decide itself what other port to use in case we already have running postgresql service on host
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    # Environment variables declared below override values in .env files
    environment:
      - POSTGRES_DB=djtwitter_db
      - POSTGRES_USER=inoxpyivan
      - POSTGRES_PASSWORD=inoxpyivanpswd

  web:
    build:
      context: . # build from Dockerfile in project root dir
    # Create a volume: we could edit the code in real-time without rebuilding container
    volumes:
      - ./dj_twitter_clone_app:/usr/src/app_djtwitter_clone
    #  maps ports and container code/database to local filesystem
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./deploy/dev/.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres_data: