version: '3.7'

services:
  db:
    container_name: postgres_container
    image: "postgres" # use latest official postgres version
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build:
      context: . # build from Dockerfile
    volumes:
      - .:/usr/src/app_djtwitter_clone
    #  maps ports and container code/database to local filesystem
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: