version: '3.7'
services:

  db:
    image: "postgres"
    ports:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_DB=djtwitter_db_prod
      - POSTGRES_USER=inoxpyivanprod
      - POSTGRES_PASSWORD=inoxpyivanpswdprod

  web:
    build: .
    image: ivanprytula/dj_twitter_clone
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./deploy/prod/.env
    command: gunicorn core_config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres_data: