version: '3.7'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=djtwitter_db
      - POSTGRES_USER=ivan-admin
      - POSTGRES_PASSWORD=rootboot

  web:
    # build from Dockerfile
    build: .
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app_djtwitter_clone
    #  maps ports and container code/database to local filesystem
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: