version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    cpu_shares: 100
    mem_limit: 3621440000
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      driver: awslogs
      options:
        awslogs-group: foodtrucks
        awslogs-region: eu-central-1
        awslogs-stream-prefix: es
  web:
    image: ivanprytula/ft:latest
    cpu_shares: 100
    mem_limit: 262144000
    ports:
      - "80:5000"
    links:
      - es
    logging:
      driver: awslogs
      options:
        awslogs-group: foodtrucks
        awslogs-region: eu-central-1
        awslogs-stream-prefix: web
