version: '3'
services:

  db:
    image: postgres
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      driver: awslogs
      options:
        awslogs-group: djtwitter
        awslogs-region: us-east-2
        awslogs-stream-prefix: db

  web:
    image: ivanprytula/dj_twitter_clone:1.0
    expose:
      - 8000
    links:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-group: djtwitter
        awslogs-region: us-east-2
        awslogs-stream-prefix: web

    nginx:
      image: ivanprytula/djtwnginx-demo:1.0
      volumes:
        - static_volume:/usr/src/app_djtwitter_clone/staticfiles
      ports:
        - 1337:80
      depends_on:
        - web