version: '3.7'
services:

  db:
    image: "postgres"
    ports:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build:
      context: ./deploy/prod
      dockerfile: Dockerfile.prod
      args:
        - buildno
    image: ivanprytula/dj_twitter_clone:${buildno}
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./deploy/prod/.env
    command: gunicorn core_config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres_data: