FROM python:3.9.0-slim-buster
LABEL maintainer="Ivan Prytula <ivanprytula87@gmail.com>"

ENV PYTONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ENV USER inoxpyivan_prod
ENV USERHOME /home/$USER
ENV APP_HOME $USERHOME/app_djtwitter_clone

WORKDIR $APP_HOME

# create the app user
RUN addgroup -S app && adduser -S app -G app
