# Generated by Django 3.1.3 on 2020-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias architecto commodi, cum, debitis error id nulla, perspiciatis provident qeq'),
        ),
    ]
