version: '3.7'
services:

  db:
    container_name: dj_demo_app_prod_postgres_container
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core_config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db



volumes:
  postgres_data: